name: Test Suit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install flex bison
    - name: make test
      run: make clean test marshaller-test
    - name: run basic test
      run: ./test
    - name: run marshaller test
      run: ./marshaller-test
